#ifndef PAX_CORE_DISPLAY_CONFIG_H
#define PAX_CORE_DISPLAY_CONFIG_H

#include "./import.h"

typedef enum Pax_Display_Visibility
{
    PAX_DISPLAY_VISIBILITY_NONE,
    PAX_DISPLAY_VISIBILITY_SHOW,
    PAX_DISPLAY_VISIBILITY_HIDE,
    PAX_DISPLAY_VISIBILITY_EXPAND,
    PAX_DISPLAY_VISIBILITY_REDUCE,
    PAX_DISPLAY_VISIBILITY_CLEAR,
}
Pax_Display_Visibility;

#endif // PAX_CORE_DISPLAY_CONFIG_H
