#ifndef PAX_CORE_DISPLAY_MESSAGE_H
#define PAX_CORE_DISPLAY_MESSAGE_H

#include "./import.h"

typedef enum Pax_Display_Message_Kind
{
    PAX_DISPLAY_MESSAGE_KIND_NONE,
    PAX_DISPLAY_MESSAGE_KIND_CLOSE,

    PAX_DISPLAY_MESSAGE_KIND_KEYBD_BUTTON,

    PAX_DISPLAY_MESSAGE_KIND_MOUSE_BUTTON,
    PAX_DISPLAY_MESSAGE_KIND_MOUSE_COORDS,
    PAX_DISPLAY_MESSAGE_KIND_MOUSE_WHEEL,
}
Pax_Display_Message_Kind;

typedef enum Pax_Keybd_Button
{
    PAX_KEYBD_BUTTON_NONE = 0,

    PAX_KEYBD_BUTTON_A, PAX_KEYBD_BUTTON_B, PAX_KEYBD_BUTTON_C, PAX_KEYBD_BUTTON_D, PAX_KEYBD_BUTTON_E, PAX_KEYBD_BUTTON_F,
    PAX_KEYBD_BUTTON_G, PAX_KEYBD_BUTTON_H, PAX_KEYBD_BUTTON_I, PAX_KEYBD_BUTTON_J, PAX_KEYBD_BUTTON_K, PAX_KEYBD_BUTTON_L,
    PAX_KEYBD_BUTTON_M, PAX_KEYBD_BUTTON_N, PAX_KEYBD_BUTTON_O, PAX_KEYBD_BUTTON_P, PAX_KEYBD_BUTTON_Q, PAX_KEYBD_BUTTON_R,
    PAX_KEYBD_BUTTON_S, PAX_KEYBD_BUTTON_T, PAX_KEYBD_BUTTON_U, PAX_KEYBD_BUTTON_V, PAX_KEYBD_BUTTON_W, PAX_KEYBD_BUTTON_X,
    PAX_KEYBD_BUTTON_Y, PAX_KEYBD_BUTTON_Z,

    PAX_KEYBD_BUTTON_ZERO, PAX_KEYBD_BUTTON_ONE, PAX_KEYBD_BUTTON_TWO,   PAX_KEYBD_BUTTON_THREE, PAX_KEYBD_BUTTON_FOUR,
    PAX_KEYBD_BUTTON_FIVE, PAX_KEYBD_BUTTON_SIX, PAX_KEYBD_BUTTON_SEVEN, PAX_KEYBD_BUTTON_EIGHT, PAX_KEYBD_BUTTON_NINE,

    PAX_KEYBD_BUTTON_F1,  PAX_KEYBD_BUTTON_F2,  PAX_KEYBD_BUTTON_F3,  PAX_KEYBD_BUTTON_F4,  PAX_KEYBD_BUTTON_F5,
    PAX_KEYBD_BUTTON_F6,  PAX_KEYBD_BUTTON_F7,  PAX_KEYBD_BUTTON_F8,  PAX_KEYBD_BUTTON_F9,  PAX_KEYBD_BUTTON_F10,
    PAX_KEYBD_BUTTON_F11, PAX_KEYBD_BUTTON_F12,

    PAX_KEYBD_BUTTON_NUM0, PAX_KEYBD_BUTTON_NUM1, PAX_KEYBD_BUTTON_NUM2, PAX_KEYBD_BUTTON_NUM3, PAX_KEYBD_BUTTON_NUM4,
    PAX_KEYBD_BUTTON_NUM5, PAX_KEYBD_BUTTON_NUM6, PAX_KEYBD_BUTTON_NUM7, PAX_KEYBD_BUTTON_NUM8, PAX_KEYBD_BUTTON_NUM9,

    PAX_KEYBD_BUTTON_SPACE,
    PAX_KEYBD_BUTTON_ENTER,
    PAX_KEYBD_BUTTON_TAB,
    PAX_KEYBD_BUTTON_ESCAPE,
    PAX_KEYBD_BUTTON_BACKSPACE,
    PAX_KEYBD_BUTTON_DELETE,
    PAX_KEYBD_BUTTON_INSERT,
    PAX_KEYBD_BUTTON_HOME,
    PAX_KEYBD_BUTTON_END,
    PAX_KEYBD_BUTTON_PAGE_UP,
    PAX_KEYBD_BUTTON_PAGE_DOWN,

    PAX_KEYBD_BUTTON_LEFT,
    PAX_KEYBD_BUTTON_RIGHT,
    PAX_KEYBD_BUTTON_UP,
    PAX_KEYBD_BUTTON_DOWN,

    PAX_KEYBD_BUTTON_SHIFT_LEFT,
    PAX_KEYBD_BUTTON_SHIFT_RIGHT,
    PAX_KEYBD_BUTTON_CTRL_LEFT,
    PAX_KEYBD_BUTTON_CTRL_RIGHT,
    PAX_KEYBD_BUTTON_ALT_LEFT,
    PAX_KEYBD_BUTTON_ALT_RIGHT,
}
Pax_Keybd_Button;

typedef struct Pax_Display_Message_Keybd_Button
{
    Pax_Keybd_Button button;
    paxiword         scan;
    paxb8            down;
}
Pax_Display_Message_Keybd_Button;

typedef enum Pax_Mouse_Button
{
    PAX_MOUSE_BUTTON_NONE,
    PAX_MOUSE_BUTTON_LEFT,
    PAX_MOUSE_BUTTON_MIDDLE,
    PAX_MOUSE_BUTTON_RIGHT,
}
Pax_Mouse_Button;

typedef struct Pax_Display_Message_Mouse_Button
{
    Pax_Mouse_Button button;
    paxb8            down;
}
Pax_Display_Message_Mouse_Button;

typedef struct Pax_Display_Message
{
    Pax_Display_Message_Kind kind;

    union
    {
        Pax_Display_Message_Keybd_Button keybd_button;
        Pax_Display_Message_Mouse_Button mouse_button;
    };
}
Pax_Display_Message;

Pax_Display_Message
pax_display_message_close();

Pax_Display_Message
pax_display_message_keybd_button(Pax_Keybd_Button button, paxb8 down, paxiword scan);

Pax_Display_Message
pax_display_message_mouse_button(Pax_Mouse_Button button, paxb8 down);

#endif // PAX_CORE_DISPLAY_MESSAGE_H
