#ifndef PAX_CORE_DISPLAY_MESSAGE_H
#define PAX_CORE_DISPLAY_MESSAGE_H

#include "./import.h"

typedef enum Pax_Display_Message_Filter
{
    PAX_DISPLAY_MESSAGE_FILTER_NONE = 0,

    PAX_DISPLAY_MESSAGE_FILTER_KEYBOARD_BUTTON = 1 << 0,

    PAX_DISPLAY_MESSAGE_FILTER_MOUSE_BUTTON = 1 << 1,
    PAX_DISPLAY_MESSAGE_FILTER_MOUSE_COORDS = 1 << 2,
    PAX_DISPLAY_MESSAGE_FILTER_MOUSE_WHEEL  = 1 << 3,
}
Pax_Display_Message_Filter;

typedef enum Pax_Display_Message_Kind
{
    PAX_DISPLAY_MESSAGE_KIND_NONE,

    PAX_DISPLAY_MESSAGE_KIND_DISPLAY_DESTROY,

    PAX_DISPLAY_MESSAGE_KIND_KEYBOARD_BUTTON,

    PAX_DISPLAY_MESSAGE_KIND_MOUSE_BUTTON,
    PAX_DISPLAY_MESSAGE_KIND_MOUSE_COORDS,
    PAX_DISPLAY_MESSAGE_KIND_MOUSE_WHEEL,
}
Pax_Display_Message_Kind;

typedef enum Pax_Keyboard_Button
{
    PAX_KEYBOARD_BUTTON_NONE = 0,

    PAX_KEYBOARD_BUTTON_A, PAX_KEYBOARD_BUTTON_B, PAX_KEYBOARD_BUTTON_C, PAX_KEYBOARD_BUTTON_D, PAX_KEYBOARD_BUTTON_E, PAX_KEYBOARD_BUTTON_F,
    PAX_KEYBOARD_BUTTON_G, PAX_KEYBOARD_BUTTON_H, PAX_KEYBOARD_BUTTON_I, PAX_KEYBOARD_BUTTON_J, PAX_KEYBOARD_BUTTON_K, PAX_KEYBOARD_BUTTON_L,
    PAX_KEYBOARD_BUTTON_M, PAX_KEYBOARD_BUTTON_N, PAX_KEYBOARD_BUTTON_O, PAX_KEYBOARD_BUTTON_P, PAX_KEYBOARD_BUTTON_Q, PAX_KEYBOARD_BUTTON_R,
    PAX_KEYBOARD_BUTTON_S, PAX_KEYBOARD_BUTTON_T, PAX_KEYBOARD_BUTTON_U, PAX_KEYBOARD_BUTTON_V, PAX_KEYBOARD_BUTTON_W, PAX_KEYBOARD_BUTTON_X,
    PAX_KEYBOARD_BUTTON_Y, PAX_KEYBOARD_BUTTON_Z,

    PAX_KEYBOARD_BUTTON_ZERO, PAX_KEYBOARD_BUTTON_ONE, PAX_KEYBOARD_BUTTON_TWO,   PAX_KEYBOARD_BUTTON_THREE, PAX_KEYBOARD_BUTTON_FOUR,
    PAX_KEYBOARD_BUTTON_FIVE, PAX_KEYBOARD_BUTTON_SIX, PAX_KEYBOARD_BUTTON_SEVEN, PAX_KEYBOARD_BUTTON_EIGHT, PAX_KEYBOARD_BUTTON_NINE,

    PAX_KEYBOARD_BUTTON_F1,  PAX_KEYBOARD_BUTTON_F2,  PAX_KEYBOARD_BUTTON_F3,  PAX_KEYBOARD_BUTTON_F4,  PAX_KEYBOARD_BUTTON_F5,
    PAX_KEYBOARD_BUTTON_F6,  PAX_KEYBOARD_BUTTON_F7,  PAX_KEYBOARD_BUTTON_F8,  PAX_KEYBOARD_BUTTON_F9,  PAX_KEYBOARD_BUTTON_F10,
    PAX_KEYBOARD_BUTTON_F11, PAX_KEYBOARD_BUTTON_F12,

    PAX_KEYBOARD_BUTTON_NUM0, PAX_KEYBOARD_BUTTON_NUM1, PAX_KEYBOARD_BUTTON_NUM2, PAX_KEYBOARD_BUTTON_NUM3, PAX_KEYBOARD_BUTTON_NUM4,
    PAX_KEYBOARD_BUTTON_NUM5, PAX_KEYBOARD_BUTTON_NUM6, PAX_KEYBOARD_BUTTON_NUM7, PAX_KEYBOARD_BUTTON_NUM8, PAX_KEYBOARD_BUTTON_NUM9,

    PAX_KEYBOARD_BUTTON_SPACE,
    PAX_KEYBOARD_BUTTON_ENTER,
    PAX_KEYBOARD_BUTTON_TAB,
    PAX_KEYBOARD_BUTTON_ESCAPE,
    PAX_KEYBOARD_BUTTON_BACKSPACE,
    PAX_KEYBOARD_BUTTON_DELETE,
    PAX_KEYBOARD_BUTTON_INSERT,
    PAX_KEYBOARD_BUTTON_HOME,
    PAX_KEYBOARD_BUTTON_END,
    PAX_KEYBOARD_BUTTON_PAGE_UP,
    PAX_KEYBOARD_BUTTON_PAGE_DOWN,

    PAX_KEYBOARD_BUTTON_LEFT,
    PAX_KEYBOARD_BUTTON_RIGHT,
    PAX_KEYBOARD_BUTTON_UP,
    PAX_KEYBOARD_BUTTON_DOWN,

    PAX_KEYBOARD_BUTTON_SHIFT_LEFT,
    PAX_KEYBOARD_BUTTON_SHIFT_RIGHT,
    PAX_KEYBOARD_BUTTON_CTRL_LEFT,
    PAX_KEYBOARD_BUTTON_CTRL_RIGHT,
    PAX_KEYBOARD_BUTTON_ALT_LEFT,
    PAX_KEYBOARD_BUTTON_ALT_RIGHT,
}
Pax_Keyboard_Button;

typedef struct Pax_Display_Message_Keyboard_Button
{
    Pax_Keyboard_Button button;
    paxiword         scan;
    paxb8            down;
}
Pax_Display_Message_Keyboard_Button;

typedef enum Pax_Mouse_Button
{
    PAX_MOUSE_BUTTON_NONE,
    PAX_MOUSE_BUTTON_LEFT,
    PAX_MOUSE_BUTTON_MIDDLE,
    PAX_MOUSE_BUTTON_RIGHT,
}
Pax_Mouse_Button;

typedef struct Pax_Display_Message_Mouse_Button
{
    Pax_Mouse_Button button;
    paxb8            down;
}
Pax_Display_Message_Mouse_Button;

typedef struct Pax_Display_Message
{
    Pax_Display_Message_Kind kind;

    union
    {
        Pax_Display_Message_Keyboard_Button keyboard_button;
        Pax_Display_Message_Mouse_Button mouse_button;
    };
}
Pax_Display_Message;

Pax_Display_Message
pax_display_message_display_destroy();

Pax_Display_Message
pax_display_message_keyboard_button(Pax_Keyboard_Button button, paxb8 down, paxiword scan);

Pax_Display_Message
pax_display_message_mouse_button(Pax_Mouse_Button button, paxb8 down);

#endif // PAX_CORE_DISPLAY_MESSAGE_H
